# yaml-language-server: $schema=https://render.com/schema/render.yaml.json
services:
  - type: web
    name: file-server
    runtime: go
    rootDir: tools/st
    buildCommand: make build
    plan: free
    startCommand: ./server
    envVars:
      - key: POSTS_DIR
        value: ./posts
    # Health check path
    healthCheckPath: /health
